# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMTV-7FTdhvu9xKH8s5A-9KHxRnWKLNA
"""

import streamlit as st
import pickle

# Load saved model and vectorizer
model = pickle.load(open("model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

st.title("📊 NLP Text Classification App")

st.write("Enter a sentence and the model will predict its class.")

# User input
text = st.text_area("Enter text here")

if st.button("Predict"):
    if text.strip() == "":
        st.warning("Please enter some text")
    else:
        # Transform input
        text_vec = vectorizer.transform([text])

        # Predict
        prediction = model.predict(text_vec)

        st.success(f"Prediction: {prediction[0]}")