# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbB3leWlJcWSz5invlIkJzYKhWZ0XRH3
"""

# =========================
# train_model.py
# =========================

import pandas as pd
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load dataset
df = pd.read_csv("AI_Human.csv")

# Remove missing values
df = df.dropna(subset=["Text", "Author"])

# Clean labels
df["Author"] = df["Author"].str.strip()

# Convert labels
df["Author"] = df["Author"].map({
    "Human": 0,
    "AI": 1
})

# Remove invalid rows
df = df.dropna(subset=["Author"])

# Features and labels
texts = df["Text"]
labels = df["Author"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    texts,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

# TF-IDF
vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Logistic Regression
model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"
)

# Train model
model.fit(X_train_vec, y_train)

# Accuracy
y_pred = model.predict(X_test_vec)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

# Save model + vectorizer
pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))

print("Model and vectorizer saved successfully!")